#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Fri Apr  7 02:24:17 EDT 2017
# Module: docker
# Submodule: 
# Command: run
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/clap"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################

function run() {

  if [ "${db_vol}" != "" ]; then
    volume_db_data="-v ${db_vol}:/var/lib/mongodb"
  fi


  cli="docker run -d --privileged --name ${app} ${volume_db_data} --restart=always -p 1194:1194/udp -p 1194:1194/tcp -p 444:443/tcp michelkaeser/docker-pritunl"
  log_debug "$cli"
  
  if [ $(docker ps | grep ${app} | wc -l) != 0 ]; then
    docker rm -f ${app}
  fi

  ${cli}

  result=$?

  eval $1="\${result}"
  eval $2="\${cli}"
}

###############################################################################
